### ISSUE TITLE
Gluestick new ExampleApp fails on Windows

### ISSUE THREAD

**Issue by slifin** [TrueCar/gluestick#178]
C:\Users\sfyir\Code>gluestick new ExampleApp
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\sfyir\Code\ExampleApp\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
 module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\sfyir\Code\ExampleApp\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

I've tried installing again with npm install gluestick -g but no change, I'm using windows 10 and node v5.7.1

**Comment by toddw** [comment]
Closing: We are dropping Windows support, not that we ever really had… Unfortunately the suggested solution for Windows is to run in a vagrant VM. This PR will hopefully make life on Windows better: https://github.com/TrueCar/gluestick/pull/388

**Comment by supergibbs** [comment]
Latest Gluestick works on the Windows 10 Creator's Update using the Ubuntu subsystem. https://blogs.msdn.microsoft.com/commandline/2017/04/11/windows-10-creators-update-whats-new-in-bashwsl-windows-console/
