### ISSUE TITLE
[1.0.0-rc.11] Error loading css from node_modules folder

### ISSUE THREAD

**Issue by marcdel** [TrueCar/gluestick#822]
# Bug

Referencing bootstrap css from node_modules folder produces a webpack css-loader error.

# Reproduction Steps

* `git clone git@github.com:marcdel/gs-rc11-bootstrap.git`
* `cd gs-rc11-bootstrap`
* `gluestick start`
* `open http://localhost:8888`

Alternative imports I have tried:
* `import "compiled/bootstrap/dist/css/bootstrap.css";`
* `import "../../../node_modules/bootstrap/dist/css/bootstrap.css";`
* `import "bootstrap/dist/css/bootstrap.css";`

# Current Result

😞

```
webpack building...

Starting to optimize CSS...
Processing main-fe78f5b88736ab84c4313db8f0369506.css...
Processed main-fe78f5b88736ab84c4313db8f0369506.css, before: 8742, after: 2875, ratio: 32.89%
./~/extract-text-webpack-plugin/loader.js?{"id":2,"omit":0,"remove":false}!./~/css-loader!./~/postcss-loader!./~/bootstrap/dist/css/bootstrap.css
Module build failed: Error
    at factoryCallback (/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/webpack/lib/Compilation.js:230:39)
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/webpack/lib/NormalModuleFactory.js:183:21
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:3694:9
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:933:13)
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:843:16
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:3691:13
    at apply (/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:21:25)
 @ ./~/bootstrap/dist/css/bootstrap.css 4:14-154 13:2-17:4 14:20-160
 @ ./src/apps/main/Index.js
 @ ./gluestick/clientEntryInit/main.js
 @ multi webpack-hot-middleware/client?path=http://localhost:8888/__webpack_hmr webpack/hot/only-dev-server babel-polyfill eventsource-polyfill ./gluestick/clientEntryInit/main.js
./~/extract-text-webpack-plugin/loader.js?{"id":2,"omit":0,"remove":false}!./~/css-loader!./~/postcss-loader!./~/bootstrap/dist/css/bootstrap.css
Module build failed: Error
    at factoryCallback (/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/webpack/lib/Compilation.js:230:39)
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/webpack/lib/NormalModuleFactory.js:234:19
    at onDoneResolving (/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/webpack/lib/NormalModuleFactory.js:183:21
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:3694:9
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:359:16
    at iteratorCallback (/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:933:13)
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:843:16
    at /Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:3691:13
    at apply (/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/async/dist/async.js:21:25)
/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/extract-text-webpack-plugin/loader.js?{"id":2,"omit":0,"remove":false}!/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/css-loader/index.js!/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/postcss-loader/index.js!/Users/mdelagrammatikas/Code/gs-rc11-bootstrap/node_modules/bootstrap/dist/css/bootstrap.css doesn't export content
webpack built 34dbb3b8b84c077a3d04 in 106ms
```

# Expected Result

😀

**Comment by zamotany** [comment]
Please run
```
npm install svg-react-loader --save && gluestick start
```
And tell if the error still occurs

**Comment by marcdel** [comment]
@zamotany yup, that fixes it!
