### ISSUE TITLE
[1.0.1] Error importing image from assets folder

### ISSUE THREAD

**Issue by marcdel** [TrueCar/gluestick#894]
# Bug

Importing an image from `apps/main/assets/images` causes an image-webpack-loader error.

# Reproduction Steps

* `git clone git@github.com:marcdel/gs-1.0.1-image-import-issue.git`
* `cd gs-1.0.1-image-import-issue.git`
* `gluestick start`

# Current Result

Error during webpack build.

```
webpack building...
./src/apps/main/assets/images/truecar-reverse-web-small.png
Module build failed: TypeError: Cannot read property 'bypassOnDebug' of null
    at Object.module.exports (/Users/mdelagrammatikas/Code/ep/test_proj/node_modules/image-webpack-loader/index.js:30:26)
 @ ./src/apps/main/components/MasterLayout.js 27:30-94
 @ ./src/apps/main/routes.js
 @ ./gluestick/clientEntryInit/main.js
 @ multi webpack-hot-middleware/client?path=http://localhost:8888/__webpack_hmr webpack/hot/only-dev-server babel-polyfill eventsource-polyfill ./gluestick/clientEntryInit/main.js
webpack built f8e91f72af426d66227f in 131ms
/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:3417
throw new Error("Module build failed: TypeError: Cannot read property 'bypassOnDebug' of null\n    at Object.module.exports (/Users/mdelagrammatikas/Code/ep/test_proj/node_modules/image-webpack-loader/index.js:30:26)");
^

Error: Module build failed: TypeError: Cannot read property 'bypassOnDebug' of null
    at Object.module.exports (/Users/mdelagrammatikas/Code/ep/test_proj/node_modules/image-webpack-loader/index.js:30:26)
    at Object.module.exports.module.exports.module.deprecate (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:3417:7)
    at __webpack_require__ (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:21:30)
    at Object.module.exports.Object.defineProperty.value (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:3049:31)
    at __webpack_require__ (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:21:30)
    at Object.module.exports.Object.defineProperty.value (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:3314:21)
    at __webpack_require__ (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:21:30)
    at Object.module.exports.Object.defineProperty.value (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:247:15)
    at __webpack_require__ (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:21:30)
    at Object.<anonymous> (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:600:15)
    at __webpack_require__ (/Users/mdelagrammatikas/Code/ep/test_proj/build/server/renderer.js:21:30)
```

# Expected Result

Webpack build succeeds.

**Comment by zamotany** [comment]
This issue was fixed with https://github.com/TrueCar/gluestick/pull/891 and it should be gone with next release. Right now you can try out `next`: just replace version in gluestick dependency with path to gluestick package and install.
